tools:
    sensiolabs_security_checker: true

filter:
    excluded_paths:
        - "examples/"
        - "tests/"
        - "vendor/"
build:
    tests:
        override:
            -
                command: phpunit --coverage-clover=my-coverage-file
                coverage:
                    file: my-coverage-file
                    format: php-clover
